name: 'Validate project'

on:
  push:
    branches: [ main ]
  pull_request:

env:
  GODOT_VERSION: ${{ vars.GODOT_VERSION }}

jobs:
  validate-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Break-A-Leg
        uses: actions/checkout@v3

      - name: Cache Godot Engine
        id: cache-godot
        uses: actions/cache@v3
        with:
          path: |-
            /usr/local/bin/godot
          key: ${{ runner.os }}-godot-${{ env.GODOT_VERSION }}

      - name: Download and config Godot Engine
        if: steps.cache-godot.outputs.cache-hit != 'true'
        shell: bash
        run: |-
          wget -q https://downloads.tuxfamily.org/godotengine/${{ env.GODOT_VERSION }}/Godot_v${{ env.GODOT_VERSION }}-stable_linux.x86_64.zip        
          unzip Godot_v${{ env.GODOT_VERSION }}-stable_linux.x86_64.zip
          mv Godot_v${{ env.GODOT_VERSION }}-stable_linux.x86_64 /usr/local/bin/godot
      
      - name: Import project assets ignoring all errors
        shell: bash
        run: |-
          godot -e --headless --quit

      - name: Validate project
        shell: bash
        run: |-
          godot --headless --quit
